In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv(r"C:\Users\HP\Downloads\all_champions_trophy_matches_results.csv")
df2=pd.read_csv(r"C:\Users\HP\Downloads\archive (1)\all_champions_trophy_players_list.csv")

In [3]:
df1

,Team1,Team2,Toss,Match days,Winner,Player of the Match,Margin,Ground,Match Date,ODI Int Match,Team1 Avg Batting Ranking,Team2 Avg Batting Ranking,Team1 Avg Bowling Ranking,Team2 Avg Bowling Ranking,Team1 Total CTs participated,Team1 Total CTs won,Team2 Total CTs participated,Team2 Total CTs won,Team1 W/L ratio over Team2
0,South Africa,West Indies,"South Africa, elected to field first",daynight,South Africa,Jacques Kallis,4 wickets,Dhaka,"Nov 1, 1998",ODI # 1364,66.58,63.42,81.50,84.92,0,0,0,0,1.000
1,India,West Indies,"India, elected to bat first",daynight,West Indies,Mervyn Dillon,6 wickets,Dhaka,"Oct 31, 1998",ODI # 1363,58.00,63.92,63.73,86.25,0,0,0,0,0.527
2,South Africa,Sri Lanka,"Sri Lanka, elected to field first",daynight,South Africa,Jacques Kallis,92 runs,Dhaka,"Oct 30, 1998",ODI # 1362,66.92,53.55,83.08,69.18,0,0,0,0,1.166
3,Pakistan,West Indies,"West Indies, elected to bat first",daynight,West Indies,Keith Arthurton,30 runs,Dhaka,"Oct 29, 1998",ODI # 1361,88.36,65.00,70.00,87.17,0,0,0,0,0.806
4,Australia,India,"Australia, elected to field first",daynight,India,Sachin Tendulkar,44 runs,Dhaka,"Oct 28, 1998",ODI # 1360,58.55,58.00,78.73,64.82,0,0,0,0,1.380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,India,Pakistan,"Pakistan, elected to field first",daynight,India,Virat Kohli,6 wickets,Dubai (DICS),"Feb 23, 2025",ODI # 4847,75.00,84.00,82.13,94.47,8,2,8,1,0.780
124,Australia,England,"Australia, elected to field first",daynight,Australia,Josh Inglis,5 wickets,Lahore,"Feb 22, 2025",ODI # 4846,83.67,84.67,89.53,88.60,8,2,8,0,1.400
125,Afghanistan,South Africa,"South Africa, elected to bat first",daynight,South Africa,Ryan Rickelton,107 runs,Karachi,"Feb 21, 2025",ODI # 4845,77.93,71.93,86.20,77.20,0,0,8,1,0.660
126,Bangladesh,India,"Bangladesh, elected to bat first",daynight,India,Shubman Gill,6 wickets,Dubai (DICS),"Feb 20, 2025",ODI # 4844,89.87,74.80,89.67,82.27,5,0,8,2,0.250
127,Pakistan,New Zealand,"Pakistan, elected to field first",daynight,New Zealand,Tom Latham,60 runs,Karachi,"Feb 19, 2025",ODI # 4843,83.47,65.43,95.47,84.14,8,1,8,1,1.150

In [4]:
df2

             Team  Year           Player Name
0     Afghanistan  2025  Hashmatullah Shahidi
1     Afghanistan  2025        Ibrahim Zadran
2     Afghanistan  2025         Ikram Alikhil
3     Afghanistan  2025    Rahmanullah Gurbaz
4     Afghanistan  2025       Sediqullah Atal
...           ...   ...                   ...
1150     Zimbabwe  2006            Piet Rinke
1151     Zimbabwe  2006        Prosper Utseya
1152     Zimbabwe  2006       Anthony Ireland
1153     Zimbabwe  2006          Ed Rainsford
1154     Zimbabwe  2006    Tafadzwa Kamungozi

[1155 rows x 3 columns]

In [5]:
duplicate_count=df1.duplicated().sum()

In [6]:
duplicate_count

np.int64(0)

In [7]:
duplicate_count=df2.duplicated().sum()

In [8]:
duplicate_count

np.int64(0)

In [9]:
df1.isnull().sum()

Team1                           0
Team2                           0
Toss                            0
Match days                      0
Winner                          0
Player of the Match             7
Margin                          0
Ground                          0
Match Date                      0
ODI Int Match                   0
Team1 Avg Batting Ranking       0
Team2 Avg Batting Ranking       0
Team1 Avg Bowling Ranking       0
Team2 Avg Bowling Ranking       0
Team1 Total CTs participated    0
Team1 Total CTs won             0
Team2 Total CTs participated    0
Team2 Total CTs won             0
Team1 W/L ratio over Team2      0
dtype: int64

In [10]:
df2.isnull().sum()

Team           0
Year           0
Player Name    0
dtype: int64

In [12]:
df1.isnull().sum()/len(df1)*100

Team1                           0.00000
Team2                           0.00000
Toss                            0.00000
Match days                      0.00000
Winner                          0.00000
Player of the Match             5.46875
Margin                          0.00000
Ground                          0.00000
Match Date                      0.00000
ODI Int Match                   0.00000
Team1 Avg Batting Ranking       0.00000
Team2 Avg Batting Ranking       0.00000
Team1 Avg Bowling Ranking       0.00000
Team2 Avg Bowling Ranking       0.00000
Team1 Total CTs participated    0.00000
Team1 Total CTs won             0.00000
Team2 Total CTs participated    0.00000
Team2 Total CTs won             0.00000
Team1 W/L ratio over Team2      0.00000
dtype: float64

In [13]:
df2.isnull().sum()/len(df2)*100

Team           0.0
Year           0.0
Player Name    0.0
dtype: float64

In [14]:
df1.head(20)

,Team1,Team2,Toss,Match days,Winner,Player of the Match,Margin,Ground,Match Date,ODI Int Match,Team1 Avg Batting Ranking,Team2 Avg Batting Ranking,Team1 Avg Bowling Ranking,Team2 Avg Bowling Ranking,Team1 Total CTs participated,Team1 Total CTs won,Team2 Total CTs participated,Team2 Total CTs won,Team1 W/L ratio over Team2
0,South Africa,West Indies,"South Africa, elected to field first",daynight,South Africa,Jacques Kallis,4 wickets,Dhaka,"Nov 1, 1998",ODI # 1364,66.58,63.42,81.50,84.92,0,0,0,0,1.000
1,India,West Indies,"India, elected to bat first",daynight,West Indies,Mervyn Dillon,6 wickets,Dhaka,"Oct 31, 1998",ODI # 1363,58.00,63.92,63.73,86.25,0,0,0,0,0.527
2,South Africa,Sri Lanka,"Sri Lanka, elected to field first",daynight,South Africa,Jacques Kallis,92 runs,Dhaka,"Oct 30, 1998",ODI # 1362,66.92,53.55,83.08,69.18,0,0,0,0,1.166
3,Pakistan,West Indies,"West Indies, elected to bat first",daynight,West Indies,Keith Arthurton,30 runs,Dhaka,"Oct 29, 1998",ODI # 1361,88.36,65.00,70.00,87.17,0,0,0,0,0.806
4,Australia,India,"Australia, elected to field first",daynight,India,Sachin Tendulkar,44 runs,Dhaka,"Oct 28, 1998",ODI # 1360,58.55,58.00,78.73,64.82,0,0,0,0,1.380
5,New Zealand,Sri Lanka,"Sri Lanka, elected to field first",daynight,Sri Lanka,Arjuna Ranatunga,5 wickets,Dhaka,"Oct 26, 1998",ODI # 1359,79.25,53.36,79.67,69.82,0,0,0,0,2.000
6,England,South Africa,"England, elected to bat first",daynight,South Africa,Daryll Cullinan,6 wickets,Dhaka,"Oct 25, 1998",ODI # 1358,75.91,67.83,90.45,84.67,0,0,0,0,0.600
7,New Zealand,Zimbabwe,"Zimbabwe, elected to bat first",daynight,New Zealand,Stephen Fleming,5 wickets,Dhaka,"Oct 24, 1998",ODI # 1357,79.58,64.55,79.92,76.00,0,0,0,0,4.000
8,India,New Zealand,"New Zealand, elected to field first",day,New Zealand,Chris Cairns,4 wickets,Nairobi (Gym),"Oct 15, 2000",ODI # 1639,75.43,63.07,70.71,74.29,1,0,1,0,1.250
9,India,South Africa,"India, elected to bat first",day,India,Sourav Ganguly,95 runs,Nairobi (Gym),"Oct 13, 2000",ODI # 1638,75.64,65.43,71.71,67.21,1,0,1,1,0.500
10,New Zealand,Pakistan,"Pakistan, elected to bat first",day,New Zealand,Shayne O'Connor,4 wickets,Nairobi (Gym),"Oct 11, 2000",ODI # 1637,64.00,68.21,74.21,66.21,1,0,1,0,0.580
11,England,South Africa,"England, elected to bat first",day,South Africa,Jacques Kallis,8 wickets,Nairobi (Gym),"Oct 10, 2000",ODI # 1636,74.93,65.29,83.93,67.50,1,0,1,1,0.466
12,New Zealand,Zimbabwe,"Zimbabwe, elected to field first",day,New Zealand,Roger Twose,64 runs,Nairobi (Gym),"Oct 9, 2000",ODI # 1635,63.86,76.08,74.79,75.31,1,0,0,0,2.800
13,Pakistan,Sri Lanka,"Sri Lanka, elected to bat first",day,Pakistan,Saeed Anwar,9 wickets,Nairobi (Gym),"Oct 8, 2000",ODI # 1634,69.07,65.93,66.79,75.93,1,0,1,0,1.857
14,Australia,India,"Australia, elected to field first",day,India,Yuvraj Singh,20 runs,Nairobi (Gym),"Oct 7, 2000",ODI # 1633,57.21,75.57,73.64,71.79,1,0,1,0,1.636
15,Bangladesh,England,"Bangladesh, elected to bat first",day,England,Alec Stewart,8 wickets,Nairobi (Gym),"Oct 5, 2000",ODI # 1632,96.00,75.13,98.36,84.27,0,0,1,0,0.000
16,Sri Lanka,West Indies,"West Indies, elected to field first",day,Sri Lanka,Avishka Gunawardene,108 runs,Nairobi (Gym),"Oct 4, 2000",ODI # 1631,67.50,82.71,76.07,88.86,0,0,1,0,0.428
17,Kenya,India,"India, elected to field first",day,India,Anil Kumble,8 wickets,Nairobi (Gym),"Oct 3, 2000",ODI # 1630,95.08,75.43,91.15,71.36,0,0,1,0,0.200
18,Sri Lanka,India,"Sri Lanka, elected to bat first",daynight,no result,NaN,-,Colombo (RPS),"Sep 30, 2002",ODI # 1889,59.00,57.38,70.91,65.46,2,0,2,0,0.743
19,Sri Lanka,India,"Sri Lanka, elected to bat first",daynight,no result,NaN,-,Colombo (RPS),"Sep 29, 2002",ODI # 1888,59.09,57.46,69.55,65.92,2,0,2,0,0.743

In [15]:
df1.head(90)

,Team1,Team2,Toss,Match days,Winner,Player of the Match,Margin,Ground,Match Date,ODI Int Match,Team1 Avg Batting Ranking,Team2 Avg Batting Ranking,Team1 Avg Bowling Ranking,Team2 Avg Bowling Ranking,Team1 Total CTs participated,Team1 Total CTs won,Team2 Total CTs participated,Team2 Total CTs won,Team1 W/L ratio over Team2
0,South Africa,West Indies,"South Africa, elected to field first",daynight,South Africa,Jacques Kallis,4 wickets,Dhaka,"Nov 1, 1998",ODI # 1364,66.58,63.42,81.50,84.92,0,0,0,0,1.000
1,India,West Indies,"India, elected to bat first",daynight,West Indies,Mervyn Dillon,6 wickets,Dhaka,"Oct 31, 1998",ODI # 1363,58.00,63.92,63.73,86.25,0,0,0,0,0.527
2,South Africa,Sri Lanka,"Sri Lanka, elected to field first",daynight,South Africa,Jacques Kallis,92 runs,Dhaka,"Oct 30, 1998",ODI # 1362,66.92,53.55,83.08,69.18,0,0,0,0,1.166
3,Pakistan,West Indies,"West Indies, elected to bat first",daynight,West Indies,Keith Arthurton,30 runs,Dhaka,"Oct 29, 1998",ODI # 1361,88.36,65.00,70.00,87.17,0,0,0,0,0.806
4,Australia,India,"Australia, elected to field first",daynight,India,Sachin Tendulkar,44 runs,Dhaka,"Oct 28, 1998",ODI # 1360,58.55,58.00,78.73,64.82,0,0,0,0,1.380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,England,India,"England, elected to field first",day,India,Ravindra Jadeja,5 runs,Birmingham,"Jun 23, 2013",ODI # 3377,70.00,70.80,71.53,79.93,6,0,6,1,0.760
86,India,Sri Lanka,"India, elected to field first",day,India,Ishant Sharma,8 wickets,Cardiff,"Jun 20, 2013",ODI # 3376,71.80,78.07,81.27,74.20,6,1,6,1,1.442
87,England,South Africa,"England, elected to field first",day,England,James Tredwell,7 wickets,The Oval,"Jun 19, 2013",ODI # 3375,70.20,85.33,72.27,79.80,6,0,5,1,0.840
88,Australia,Sri Lanka,"Australia, elected to field first",daynight,Sri Lanka,Mahela Jayawardene,20 runs,The Oval,"Jun 17, 2013",ODI # 3374,72.53,78.80,74.40,74.20,6,2,6,1,1.833
89,England,New Zealand,"New Zealand, elected to field first",day,England,Alastair Cook,10 runs,Cardiff,"Jun 16, 2013",ODI # 3373,69.87,77.27,72.60,75.27,6,0,6,1,0.842

In [19]:
df1["Player of the Match"]=df1["Player of the Match"].fillna("unknown")

In [20]:
df1

,Team1,Team2,Toss,Match days,Winner,Player of the Match,Margin,Ground,Match Date,ODI Int Match,Team1 Avg Batting Ranking,Team2 Avg Batting Ranking,Team1 Avg Bowling Ranking,Team2 Avg Bowling Ranking,Team1 Total CTs participated,Team1 Total CTs won,Team2 Total CTs participated,Team2 Total CTs won,Team1 W/L ratio over Team2
0,South Africa,West Indies,"South Africa, elected to field first",daynight,South Africa,Jacques Kallis,4 wickets,Dhaka,"Nov 1, 1998",ODI # 1364,66.58,63.42,81.50,84.92,0,0,0,0,1.000
1,India,West Indies,"India, elected to bat first",daynight,West Indies,Mervyn Dillon,6 wickets,Dhaka,"Oct 31, 1998",ODI # 1363,58.00,63.92,63.73,86.25,0,0,0,0,0.527
2,South Africa,Sri Lanka,"Sri Lanka, elected to field first",daynight,South Africa,Jacques Kallis,92 runs,Dhaka,"Oct 30, 1998",ODI # 1362,66.92,53.55,83.08,69.18,0,0,0,0,1.166
3,Pakistan,West Indies,"West Indies, elected to bat first",daynight,West Indies,Keith Arthurton,30 runs,Dhaka,"Oct 29, 1998",ODI # 1361,88.36,65.00,70.00,87.17,0,0,0,0,0.806
4,Australia,India,"Australia, elected to field first",daynight,India,Sachin Tendulkar,44 runs,Dhaka,"Oct 28, 1998",ODI # 1360,58.55,58.00,78.73,64.82,0,0,0,0,1.380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,India,Pakistan,"Pakistan, elected to field first",daynight,India,Virat Kohli,6 wickets,Dubai (DICS),"Feb 23, 2025",ODI # 4847,75.00,84.00,82.13,94.47,8,2,8,1,0.780
124,Australia,England,"Australia, elected to field first",daynight,Australia,Josh Inglis,5 wickets,Lahore,"Feb 22, 2025",ODI # 4846,83.67,84.67,89.53,88.60,8,2,8,0,1.400
125,Afghanistan,South Africa,"South Africa, elected to bat first",daynight,South Africa,Ryan Rickelton,107 runs,Karachi,"Feb 21, 2025",ODI # 4845,77.93,71.93,86.20,77.20,0,0,8,1,0.660
126,Bangladesh,India,"Bangladesh, elected to bat first",daynight,India,Shubman Gill,6 wickets,Dubai (DICS),"Feb 20, 2025",ODI # 4844,89.87,74.80,89.67,82.27,5,0,8,2,0.250
127,Pakistan,New Zealand,"Pakistan, elected to field first",daynight,New Zealand,Tom Latham,60 runs,Karachi,"Feb 19, 2025",ODI # 4843,83.47,65.43,95.47,84.14,8,1,8,1,1.150

In [21]:
df1.head(50)

,Team1,Team2,Toss,Match days,Winner,Player of the Match,Margin,Ground,Match Date,ODI Int Match,Team1 Avg Batting Ranking,Team2 Avg Batting Ranking,Team1 Avg Bowling Ranking,Team2 Avg Bowling Ranking,Team1 Total CTs participated,Team1 Total CTs won,Team2 Total CTs participated,Team2 Total CTs won,Team1 W/L ratio over Team2
0,South Africa,West Indies,"South Africa, elected to field first",daynight,South Africa,Jacques Kallis,4 wickets,Dhaka,"Nov 1, 1998",ODI # 1364,66.58,63.42,81.50,84.92,0,0,0,0,1.000
1,India,West Indies,"India, elected to bat first",daynight,West Indies,Mervyn Dillon,6 wickets,Dhaka,"Oct 31, 1998",ODI # 1363,58.00,63.92,63.73,86.25,0,0,0,0,0.527
2,South Africa,Sri Lanka,"Sri Lanka, elected to field first",daynight,South Africa,Jacques Kallis,92 runs,Dhaka,"Oct 30, 1998",ODI # 1362,66.92,53.55,83.08,69.18,0,0,0,0,1.166
3,Pakistan,West Indies,"West Indies, elected to bat first",daynight,West Indies,Keith Arthurton,30 runs,Dhaka,"Oct 29, 1998",ODI # 1361,88.36,65.00,70.00,87.17,0,0,0,0,0.806
4,Australia,India,"Australia, elected to field first",daynight,India,Sachin Tendulkar,44 runs,Dhaka,"Oct 28, 1998",ODI # 1360,58.55,58.00,78.73,64.82,0,0,0,0,1.380
5,New Zealand,Sri Lanka,"Sri Lanka, elected to field first",daynight,Sri Lanka,Arjuna Ranatunga,5 wickets,Dhaka,"Oct 26, 1998",ODI # 1359,79.25,53.36,79.67,69.82,0,0,0,0,2.000
6,England,South Africa,"England, elected to bat first",daynight,South Africa,Daryll Cullinan,6 wickets,Dhaka,"Oct 25, 1998",ODI # 1358,75.91,67.83,90.45,84.67,0,0,0,0,0.600
7,New Zealand,Zimbabwe,"Zimbabwe, elected to bat first",daynight,New Zealand,Stephen Fleming,5 wickets,Dhaka,"Oct 24, 1998",ODI # 1357,79.58,64.55,79.92,76.00,0,0,0,0,4.000
8,India,New Zealand,"New Zealand, elected to field first",day,New Zealand,Chris Cairns,4 wickets,Nairobi (Gym),"Oct 15, 2000",ODI # 1639,75.43,63.07,70.71,74.29,1,0,1,0,1.250
9,India,South Africa,"India, elected to bat first",day,India,Sourav Ganguly,95 runs,Nairobi (Gym),"Oct 13, 2000",ODI # 1638,75.64,65.43,71.71,67.21,1,0,1,1,0.500
10,New Zealand,Pakistan,"Pakistan, elected to bat first",day,New Zealand,Shayne O'Connor,4 wickets,Nairobi (Gym),"Oct 11, 2000",ODI # 1637,64.00,68.21,74.21,66.21,1,0,1,0,0.580
11,England,South Africa,"England, elected to bat first",day,South Africa,Jacques Kallis,8 wickets,Nairobi (Gym),"Oct 10, 2000",ODI # 1636,74.93,65.29,83.93,67.50,1,0,1,1,0.466
12,New Zealand,Zimbabwe,"Zimbabwe, elected to field first",day,New Zealand,Roger Twose,64 runs,Nairobi (Gym),"Oct 9, 2000",ODI # 1635,63.86,76.08,74.79,75.31,1,0,0,0,2.800
13,Pakistan,Sri Lanka,"Sri Lanka, elected to bat first",day,Pakistan,Saeed Anwar,9 wickets,Nairobi (Gym),"Oct 8, 2000",ODI # 1634,69.07,65.93,66.79,75.93,1,0,1,0,1.857
14,Australia,India,"Australia, elected to field first",day,India,Yuvraj Singh,20 runs,Nairobi (Gym),"Oct 7, 2000",ODI # 1633,57.21,75.57,73.64,71.79,1,0,1,0,1.636
15,Bangladesh,England,"Bangladesh, elected to bat first",day,England,Alec Stewart,8 wickets,Nairobi (Gym),"Oct 5, 2000",ODI # 1632,96.00,75.13,98.36,84.27,0,0,1,0,0.000
16,Sri Lanka,West Indies,"West Indies, elected to field first",day,Sri Lanka,Avishka Gunawardene,108 runs,Nairobi (Gym),"Oct 4, 2000",ODI # 1631,67.50,82.71,76.07,88.86,0,0,1,0,0.428
17,Kenya,India,"India, elected to field first",day,India,Anil Kumble,8 wickets,Nairobi (Gym),"Oct 3, 2000",ODI # 1630,95.08,75.43,91.15,71.36,0,0,1,0,0.200
18,Sri Lanka,India,"Sri Lanka, elected to bat first",daynight,no result,unknown,-,Colombo (RPS),"Sep 30, 2002",ODI # 1889,59.00,57.38,70.91,65.46,2,0,2,0,0.743
19,Sri Lanka,India,"Sri Lanka, elected to bat first",daynight,no result,unknown,-,Colombo (RPS),"Sep 29, 2002",ODI # 1888,59.09,57.46,69.55,65.92,2,0,2,0,0.743
20,Sri Lanka,Australia,"Australia, elected to bat first",daynight,Sri Lanka,Aravinda de Silva,7 wickets,Colombo (RPS),"Sep 27, 2002",ODI # 1887,59.64,57.42,71.09,68.00,2,0,2,0,0.464
21,India,South Africa,"India, elected to bat first",daynight,India,Virender Sehwag,10 runs,Colombo (RPS),"Sep 25, 2002",ODI # 1886,58.38,61.93,66.00,69.47,2,0,2,1,0.518
22,Bangladesh,New Zealand,"Bangladesh, elected to field first",daynight,New Zealand,Shane Bond,167 runs,Colombo (SSC),"Sep 23, 2002",ODI # 1885,98.07,76.42,95.43,70.67,1,0,2,1,0.000
23,England,India,"England, elected to bat first",daynight,India,Virender Sehwag,8 wickets,Colombo (RPS),"Sep 22, 2002",ODI # 1884,75.83,59.54,88.00,66.77,2,0,2,0,1.095
24,Netherlands,Pakistan,"Netherlands, elected to bat first",day,Pakistan,Shahid Afridi,9 wickets,Colombo (SSC),"Sep 21, 2002",ODI # 1883,101.00,67.09,101.00,61.09,0,0,2,0,0.000
25,Kenya,South Africa,"South Africa, elected to bat first",daynight,South Africa,Herschelle Gibbs,176 runs,Colombo (RPS),"Sep 20, 2002",ODI # 1882,93.67,61.87,88.75,69.27,1,0,2,1,0.000
26,Australia,Bangladesh,"Bangladesh, elected to bat first",day,Australia,Jason Gillespie,9 wickets,Colombo (SSC),"Sep 19, 2002",ODI # 1881,57.50,98.00,68.50,95.07,2,0,1,0,2.000
27,England,Zimbabwe,"England, elected to bat first",daynight,England,Marcus Trescothick,108 runs,Colombo (RPS),"Sep 18, 2002",ODI # 1880,75.58,69.92,89.08,83.67,2,0,2,0,2.000
28,Kenya,West Indies,"West Indies, elected to bat first",day,West Indies,Brian Lara,29 runs,Colombo (SSC),"Sep 17, 2002",ODI # 1879,93.50,60.36,88.67,75.45,1,0,2,0,0.333
29,Sri Lanka,Netherlands,"Sri Lanka, elected to bat first",daynight,Sri Lanka,Marvan Atapattu,206 runs,Colombo (RPS),"Sep 16, 2002",ODI # 1878,59.55,101.00,70.55,101.00,2,0,0,0,2.000
30,Australia,New Zealand,"Australia, elected to bat first",day,Australia,Glenn McGrath,164 runs,Colombo (SSC),"Sep 15, 2002",ODI # 1877,57.75,76.67,68.67,71.00,2,0,2,1,2.240
31,India,Zimbabwe,"India, elected to bat first",daynight,India,Mohammad Kaif,14 runs,Colombo (RPS),"Sep 14, 2002",ODI # 1876,60.00,70.50,66.92,84.17,2,0,2,0,4.000
32,South Africa,West Indies,"South Africa, elected to field first",day,South Africa,Jonty Rhodes,2 wickets,Colombo (SSC),"Sep 13, 2002",ODI # 1875,61.93,60.64,69.00,76.27,2,1,2,0,2.125
33,Sri Lanka,Pakistan,"Pakistan, elected to bat first",daynight,Sri Lanka,Sanath Jayasuriya,8 wickets,Colombo (RPS),"Sep 12, 2002",ODI # 1874,59.45,67.82,70.73,60.09,2,0,2,0,0.586
34,England,West Indies,"West Indies, elected to field first",day,West Indies,Ian Bradshaw,2 wickets,The Oval,"Sep 25, 2004",ODI # 2182,64.27,67.71,70.36,77.21,3,0,3,0,0.805
35,Pakistan,West Indies,"Pakistan, elected to bat first",day,West Indies,Ramnaresh Sarwan,7 wickets,Southampton,"Sep 22, 2004",ODI # 2181,57.75,67.71,67.83,78.14,3,0,3,0,0.805
36,England,Australia,"England, elected to field first",day,England,Michael Vaughan,6 wickets,Birmingham,"Sep 21, 2004",ODI # 2180,65.55,51.75,70.36,62.00,3,0,3,0,0.704
37,India,Pakistan,"Pakistan, elected to field first",day,Pakistan,Mohammad Yousuf,3 wickets,Birmingham,"Sep 19, 2004",ODI # 2179,65.50,58.08,70.58,68.83,3,1,3,0,0.589
38,South Africa,West Indies,"West Indies, elected to field first",day,West Indies,Ramnaresh Sarwan,5 wickets,The Oval,"Sep 18, 2004",ODI # 2178,53.00,68.29,68.45,78.64,3,1,3,0,2.100
39,England,Sri Lanka,"Sri Lanka, elected to field first",day,England,Andrew Flintoff,49 runs,Southampton,"Sep 17, 2004",ODI # 2177,66.73,60.82,70.45,70.09,3,0,3,1,1.384
40,Australia,New Zealand,"Australia, elected to field first",day,Australia,Andrew Symonds,7 wickets,The Oval,"Sep 16, 2004",ODI # 2176,52.08,56.42,63.17,58.25,3,0,3,1,2.440
41,Bangladesh,West Indies,"Bangladesh, elected to field first",day,West Indies,Chris Gayle,138 runs,Southampton,"Sep 15, 2004",ODI # 2175,95.83,68.57,94.00,80.50,2,0,3,0,0.000
42,Sri Lanka,Zimbabwe,"Sri Lanka, elected to field first",day,Sri Lanka,Elton Chigumbura,4 wickets,The Oval,"Sep 14, 2004",ODI # 2173,61.18,88.27,71.09,97.09,3,1,3,0,4.500
43,Kenya,Pakistan,"Pakistan, elected to field first",day,Pakistan,Shahid Afridi,7 wickets,Birmingham,"Sep 14, 2004",ODI # 2174,100.33,57.58,96.33,69.08,2,0,3,0,0.000
44,Australia,U.S.A.,"Australia, elected to field first",day,Australia,Michael Kasprowicz,9 wickets,Southampton,"Sep 13, 2004",ODI # 2172,52.25,101.00,63.08,101.00,3,0,0,0,0.000
45,Bangladesh,South Africa,"Bangladesh, elected to bat first",day,South Africa,Charl Langeveldt,9 wickets,Birmingham,"Sep 12, 2004",ODI # 2171,95.25,53.45,93.92,70.55,2,0,3,1,0.000
46,India,Kenya,"Kenya, elected to field first",day,India,Sourav Ganguly,98 runs,Southampton,"Sep 11, 2004",ODI # 2170,65.25,99.67,70.58,96.42,3,1,2,0,5.000
47,England,Zimbabwe,"Zimbabwe, elected to field first",day,England,Paul Collingwood,152 runs,Birmingham,"Sep 10, 2004",ODI # 2168,67.36,89.18,71.18,96.82,3,0,3,0,2.000
48,New Zealand,U.S.A.,"United States of America, elected to field first",day,New Zealand,Nathan Astle,210 runs,The Oval,"Sep 10, 2004",ODI # 2169,57.25,101.00,58.17,101.00,3,1,0,0,2.000
49,Australia,West Indies,"West Indies, elected to bat first",daynight,Australia,Shane Watson\n,8 wickets,Brabourne,"Nov 5, 2006",ODI # 2443,59.58,64.21,59.67,65.21,4,0,4,1,0.910

In [22]:
df1.isnull().sum()

Team1                           0
Team2                           0
Toss                            0
Match days                      0
Winner                          0
Player of the Match             0
Margin                          0
Ground                          0
Match Date                      0
ODI Int Match                   0
Team1 Avg Batting Ranking       0
Team2 Avg Batting Ranking       0
Team1 Avg Bowling Ranking       0
Team2 Avg Bowling Ranking       0
Team1 Total CTs participated    0
Team1 Total CTs won             0
Team2 Total CTs participated    0
Team2 Total CTs won             0
Team1 W/L ratio over Team2      0
dtype: int64

In [24]:
df1.to_csv("cleaneddata.csv",index=False)

In [ ]:
df2.to_csv("cleaneddata2.csv",